apiVersion: v1
kind: Service
metadata:
  name: conductor-server
  labels:
    app: conductor-server
spec:
  type: LoadBalancer
  selector:
    app: conductor-server
  ports:
    - name: http
      port: 80
      targetPort: 8080

