FROM alpine:3
CMD printf '\n\
============================================================\n\
  conductoross/conductor-standalone IS DEPRECATED\n\
============================================================\n\
\n\
  This image has not been updated since December 2023.\n\
  Last published version: Conductor 3.15.0\n\
  Current release:        Conductor 3.23.0+\n\
\n\
  DO NOT USE this image for new deployments.\n\
\n\
  Use instead:\n\
    docker pull conductoross/conductor:latest\n\
\n\
  Getting started:\n\
    https://github.com/conductor-oss/getting-started\n\
\n\
============================================================\n\
\n' && exit 1
