// Code generated by protoc-gen-go. DO NOT EDIT.
// source: model/subworkflowparams.proto

package model // import "github.com/netflix/conductor/client/gogrpc/conductor/model"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SubWorkflowParams struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version              int32    `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubWorkflowParams) Reset()         { *m = SubWorkflowParams{} }
func (m *SubWorkflowParams) String() string { return proto.CompactTextString(m) }
func (*SubWorkflowParams) ProtoMessage()    {}
func (*SubWorkflowParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_subworkflowparams_247aeccdfb62062e, []int{0}
}
func (m *SubWorkflowParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubWorkflowParams.Unmarshal(m, b)
}
func (m *SubWorkflowParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubWorkflowParams.Marshal(b, m, deterministic)
}
func (dst *SubWorkflowParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubWorkflowParams.Merge(dst, src)
}
func (m *SubWorkflowParams) XXX_Size() int {
	return xxx_messageInfo_SubWorkflowParams.Size(m)
}
func (m *SubWorkflowParams) XXX_DiscardUnknown() {
	xxx_messageInfo_SubWorkflowParams.DiscardUnknown(m)
}

var xxx_messageInfo_SubWorkflowParams proto.InternalMessageInfo

func (m *SubWorkflowParams) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SubWorkflowParams) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func init() {
	proto.RegisterType((*SubWorkflowParams)(nil), "conductor.proto.SubWorkflowParams")
}

func init() {
	proto.RegisterFile("model/subworkflowparams.proto", fileDescriptor_subworkflowparams_247aeccdfb62062e)
}

var fileDescriptor_subworkflowparams_247aeccdfb62062e = []byte{
	// 183 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0xcd, 0xcd, 0x4f, 0x49,
	0xcd, 0xd1, 0x2f, 0x2e, 0x4d, 0x2a, 0xcf, 0x2f, 0xca, 0x4e, 0xcb, 0xc9, 0x2f, 0x2f, 0x48, 0x2c,
	0x4a, 0xcc, 0x2d, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x4f, 0xce, 0xcf, 0x4b, 0x29,
	0x4d, 0x2e, 0xc9, 0x2f, 0x82, 0x08, 0x28, 0x39, 0x72, 0x09, 0x06, 0x97, 0x26, 0x85, 0x43, 0xd5,
	0x06, 0x80, 0xd5, 0x0a, 0x09, 0x71, 0xb1, 0xe4, 0x25, 0xe6, 0xa6, 0x4a, 0x30, 0x2a, 0x30, 0x6a,
	0x70, 0x06, 0x81, 0xd9, 0x42, 0x12, 0x5c, 0xec, 0x65, 0xa9, 0x45, 0xc5, 0x99, 0xf9, 0x79, 0x12,
	0x4c, 0x0a, 0x8c, 0x1a, 0xac, 0x41, 0x30, 0xae, 0x53, 0x1e, 0x97, 0x74, 0x72, 0x7e, 0xae, 0x5e,
	0x5e, 0x6a, 0x49, 0x5a, 0x4e, 0x66, 0x85, 0x1e, 0x9a, 0x0d, 0x4e, 0xc2, 0x18, 0xe6, 0x07, 0x24,
	0x45, 0x59, 0xa5, 0x67, 0x96, 0x64, 0x94, 0x26, 0xe9, 0x25, 0xe7, 0xe7, 0xea, 0x43, 0x35, 0xea,
	0xc3, 0x35, 0xea, 0x27, 0xe7, 0x64, 0xa6, 0xe6, 0x95, 0xe8, 0xa7, 0xe7, 0xa7, 0x17, 0x15, 0x24,
	0x23, 0x89, 0x83, 0xfd, 0x96, 0xc4, 0x06, 0x36, 0xd7, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x52,
	0x9c, 0xc5, 0x01, 0xeb, 0x00, 0x00, 0x00,
}
