export const WORKFLOW_STATUS = {
  RUNNING: "RUNNING",
  COMPLETED: "COMPLETED",
  FAILED: "FAILED",
  TIMED_OUT: "TIMED_OUT",
  TERMINATED: "TERMINATED",
  PAUSED: "PAUSED",
};

export const ZOOMING_STEP = 0.1;

export const TEST_TASK_TYPES = [
  "HTTP",
  "HTTP_POLL",
  "INLINE",
  "DO_WHILE",
  "DYNAMIC",
  "UPDATE_SECRET",
  "SWITCH",
  "QUERY_PROCESSOR",
  "JSON_JQ_TRANSFORM",
  "LLM_TEXT_COMPLETE",
  "LLM_GENERATE_EMBEDDINGS",
  "LLM_GET_EMBEDDINGS",
  "LLM_STORE_EMBEDDINGS",
  "LLM_SEARCH_INDEX",
  "LLM_INDEX_DOCUMENT",
  "LLM_INDEX_TEXT",
  "GET_WORKFLOW",
];
