
clean-db:
	docker volume rm grpc_conductor_mysql

compose-build:
	docker-compose build

dependencies-up:
	docker-compose up -d mysql elasticsearch

dependencies-down:
	docker-compose down

stack-up:
	docker-compose up

stack-down:
	docker-compose down
