apiVersion: v1
kind: Service
metadata:
  name: conductor-ui-service
  labels:
    app: conductor-ui
spec:
  selector:
    app: conductor-ui
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
  type: LoadBalancer  # Change to ClusterIP if you want internal-only access

