apiVersion: v1
kind: Service
metadata:
  name: conductor-service
spec:
  selector:
    app: conductor
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: api
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer  # Use NodePort if not on cloud or no LoadBalancer support

