// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpc/search.proto

package grpc // import "github.com/netflix/conductor/client/gogrpc/conductor/grpc"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import model "github.com/netflix/conductor/client/gogrpc/conductor/model"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SearchRequest struct {
	Start                int32    `protobuf:"varint,1,opt,name=start" json:"start,omitempty"`
	Size                 int32    `protobuf:"varint,2,opt,name=size" json:"size,omitempty"`
	Sort                 string   `protobuf:"bytes,3,opt,name=sort" json:"sort,omitempty"`
	FreeText             string   `protobuf:"bytes,4,opt,name=free_text,json=freeText" json:"free_text,omitempty"`
	Query                string   `protobuf:"bytes,5,opt,name=query" json:"query,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchRequest) Reset()         { *m = SearchRequest{} }
func (m *SearchRequest) String() string { return proto.CompactTextString(m) }
func (*SearchRequest) ProtoMessage()    {}
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_search_4602c68037d6c24f, []int{0}
}
func (m *SearchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchRequest.Unmarshal(m, b)
}
func (m *SearchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchRequest.Marshal(b, m, deterministic)
}
func (dst *SearchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchRequest.Merge(dst, src)
}
func (m *SearchRequest) XXX_Size() int {
	return xxx_messageInfo_SearchRequest.Size(m)
}
func (m *SearchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchRequest proto.InternalMessageInfo

func (m *SearchRequest) GetStart() int32 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *SearchRequest) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *SearchRequest) GetSort() string {
	if m != nil {
		return m.Sort
	}
	return ""
}

func (m *SearchRequest) GetFreeText() string {
	if m != nil {
		return m.FreeText
	}
	return ""
}

func (m *SearchRequest) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

type WorkflowSummarySearchResult struct {
	TotalHits            int64                    `protobuf:"varint,1,opt,name=total_hits,json=totalHits" json:"total_hits,omitempty"`
	Results              []*model.WorkflowSummary `protobuf:"bytes,2,rep,name=results" json:"results,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *WorkflowSummarySearchResult) Reset()         { *m = WorkflowSummarySearchResult{} }
func (m *WorkflowSummarySearchResult) String() string { return proto.CompactTextString(m) }
func (*WorkflowSummarySearchResult) ProtoMessage()    {}
func (*WorkflowSummarySearchResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_search_4602c68037d6c24f, []int{1}
}
func (m *WorkflowSummarySearchResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WorkflowSummarySearchResult.Unmarshal(m, b)
}
func (m *WorkflowSummarySearchResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WorkflowSummarySearchResult.Marshal(b, m, deterministic)
}
func (dst *WorkflowSummarySearchResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WorkflowSummarySearchResult.Merge(dst, src)
}
func (m *WorkflowSummarySearchResult) XXX_Size() int {
	return xxx_messageInfo_WorkflowSummarySearchResult.Size(m)
}
func (m *WorkflowSummarySearchResult) XXX_DiscardUnknown() {
	xxx_messageInfo_WorkflowSummarySearchResult.DiscardUnknown(m)
}

var xxx_messageInfo_WorkflowSummarySearchResult proto.InternalMessageInfo

func (m *WorkflowSummarySearchResult) GetTotalHits() int64 {
	if m != nil {
		return m.TotalHits
	}
	return 0
}

func (m *WorkflowSummarySearchResult) GetResults() []*model.WorkflowSummary {
	if m != nil {
		return m.Results
	}
	return nil
}

func init() {
	proto.RegisterType((*SearchRequest)(nil), "com.netflix.conductor.grpc.SearchRequest")
	proto.RegisterType((*WorkflowSummarySearchResult)(nil), "com.netflix.conductor.grpc.WorkflowSummarySearchResult")
}

func init() { proto.RegisterFile("grpc/search.proto", fileDescriptor_search_4602c68037d6c24f) }

var fileDescriptor_search_4602c68037d6c24f = []byte{
	// 292 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x51, 0xcf, 0x4b, 0x33, 0x31,
	0x10, 0x65, 0xfb, 0xe3, 0xfb, 0xda, 0x88, 0x07, 0x83, 0x87, 0xd0, 0x22, 0x94, 0x9e, 0x7a, 0x90,
	0x04, 0xf4, 0xe4, 0xb5, 0xa0, 0x78, 0x94, 0xad, 0x20, 0x78, 0x29, 0xdb, 0x74, 0xba, 0x1b, 0xcc,
	0x6e, 0xda, 0x64, 0x42, 0xb7, 0x9e, 0x3c, 0xf8, 0x87, 0xcb, 0xce, 0xb6, 0x0a, 0xe2, 0x6d, 0xde,
	0x9b, 0x99, 0xf7, 0x5e, 0x32, 0xec, 0x22, 0xf7, 0x5b, 0xad, 0x02, 0x64, 0x5e, 0x17, 0x72, 0xeb,
	0x1d, 0x3a, 0x3e, 0xd2, 0xae, 0x94, 0x15, 0xe0, 0xc6, 0x9a, 0x5a, 0x6a, 0x57, 0xad, 0xa3, 0x46,
	0xe7, 0x65, 0x33, 0x38, 0x1a, 0x97, 0x6e, 0x0d, 0x56, 0xed, 0x9d, 0x7f, 0xdb, 0x58, 0xb7, 0x0f,
	0xb1, 0x2c, 0x33, 0x7f, 0x68, 0x17, 0xa7, 0x1f, 0x09, 0x3b, 0x5f, 0x90, 0x52, 0x0a, 0xbb, 0x08,
	0x01, 0xf9, 0x25, 0xeb, 0x07, 0xcc, 0x3c, 0x8a, 0x64, 0x92, 0xcc, 0xfa, 0x69, 0x0b, 0x38, 0x67,
	0xbd, 0x60, 0xde, 0x41, 0x74, 0x88, 0xa4, 0x9a, 0x38, 0xe7, 0x51, 0x74, 0x27, 0xc9, 0x6c, 0x98,
	0x52, 0xcd, 0xc7, 0x6c, 0xb8, 0xf1, 0x00, 0x4b, 0x84, 0x1a, 0x45, 0x8f, 0x1a, 0x83, 0x86, 0x78,
	0x86, 0x9a, 0xa4, 0x77, 0x11, 0xfc, 0x41, 0xf4, 0xa9, 0xd1, 0x82, 0xe9, 0x67, 0xc2, 0xc6, 0x2f,
	0xc7, 0x70, 0x8b, 0x36, 0xdc, 0x29, 0x51, 0x88, 0x16, 0xf9, 0x15, 0x63, 0xe8, 0x30, 0xb3, 0xcb,
	0xc2, 0x60, 0xa0, 0x54, 0xdd, 0x74, 0x48, 0xcc, 0xa3, 0xc1, 0xc0, 0x1f, 0xd8, 0x7f, 0x4f, 0x83,
	0x41, 0x74, 0x26, 0xdd, 0xd9, 0xd9, 0xcd, 0xb5, 0xfc, 0xfb, 0x33, 0xe8, 0xc1, 0xf2, 0x97, 0x53,
	0x7a, 0x5a, 0x9e, 0xdf, 0xcf, 0x07, 0xad, 0xed, 0xd3, 0xea, 0xf5, 0x2e, 0x37, 0x58, 0xc4, 0x55,
	0x23, 0xa4, 0x8e, 0x42, 0xea, 0x5b, 0x48, 0x69, 0x6b, 0xa0, 0x42, 0x95, 0x3b, 0xba, 0xc3, 0x0f,
	0xdf, 0xc0, 0xd5, 0x3f, 0xb2, 0xb9, 0xfd, 0x0a, 0x00, 0x00, 0xff, 0xff, 0xcf, 0x03, 0x79, 0x98,
	0xa5, 0x01, 0x00, 0x00,
}
