/**
 * Maps integration type identifiers to their iconName, only where they differ.
 * Used by IntegrationIcon to resolve the correct icon when the passed value
 * is an integration type rather than a direct icon name.
 */
export const integrationIconMap: Record<string, string> = {
  azure_openai: "azureOpenAI",
  openai: "openAI",
  vertex_ai: "vertexAI",
  vertex_ai_gemini: "vertexAI",
  huggingface: "huggingFace",
  pineconedb: "pinecone",
  weaviatedb: "weaviate",
  pgvectordb: "pgvector",
  mongovectordb: "mongovector",
  aws_sqs: "aws",
  aws_bedrock_anthropic: "aws",
  aws_bedrock_cohere: "aws",
  aws_bedrock_titan: "aws",
  "slack-webhook-v2": "slack",
  "google-calendar-mcp": "googlecalendar",
  "grafana-mcp": "grafana",
  "wordpress-com": "wordpress",
  "pagerduty-inline": "pagerduty",
  "gmail-mcp-v2": "gmail",
  "firebase-firestore-mcp-v5": "firebase-firestore",
  "clickhouse-mcp-v2": "clickhouse",
  "google-cloud-storage-mcp": "google-cloud-storage",
  "redis-mcp": "redis",
  "aws-ses-mcp": "aws-ses",
  "stripe-mcp": "stripe",
  "slack-mcp": "slack",
  "google-analytics": "googleanalytics",
  "google-drive-mcp": "google-drive",
  "google-docs-mcp": "google-docs",
  "google-slides-mcp": "google-slides",
  "google-cloud-functions-mcp": "google-cloud-functions",
  "google-ads": "googleads",
  "aws-lambda-mcp": "aws-lambda",
  "mysql-mcp": "mysql",
  "postgres-mcp": "postgres",
  "google-sheets-mcp": "google-sheets",
  "aws-sns-mcp": "aws-sns",
};
