/*
 * Copyright 2025 Conductor Authors.
 * <p>
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 * <p>
 * http://www.apache.org/licenses/LICENSE-2.0
 * <p>
 * Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
 * an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations under the License.
 */
package org.conductoross.conductor.ai.models;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;

import org.conductoross.conductor.common.Documented;

import com.netflix.conductor.common.metadata.SchemaDef;

import lombok.Data;
import lombok.EqualsAndHashCode;

@Data
@EqualsAndHashCode(callSuper = true)
public class ChatCompletion extends LLMWorkerInput {

    public static final String NAME = "LLM_CHAT_COMPLETE";

    private String instructions;

    @Documented(usage = "History of messages")
    private List<ChatMessage> messages = new ArrayList<>();

    @Documented(
            usage =
                    "Produces JSON as output if set to true.  Depending on the model you MUST including JSON word as part of the prompt")
    private boolean jsonOutput;

    @Documented(usage = "Enable Google Search Retrieval for Gemini models")
    private boolean googleSearchRetrieval;

    @Documented(
            usage =
                    "Optional schema for the prompt inputs.  If supplied, the inputs MUST conform to the schema")
    private SchemaDef inputSchema;

    @Documented(
            usage =
                    """
                        Output schema for the response generated by LLM.  Useful when using #jsonOutput.  If specified, the LLM output is validated against the schema.
                        If the validation fails, the request is retried N number of times.  Default value for N is 3 and depends on the retryCount defined in the taskDefinition.
                        When retrying, no waits or backoff are applied.
                        """)
    private SchemaDef outputSchema;

    private String userInput;

    @Documented(
            usage =
                    """
                        Tools to be used.  Tools MUST be registered conductor workers or supported integrations
                        """)
    private List<ToolSpec> tools = new ArrayList<>();

    @Documented(usage = "Integrations for the mcp tools")
    private Map<String, ChatMessage.Role> participants = Map.of();

    // refers to HTTP content type
    private String outputMimeType;

    // Used for thinking models
    @Documented(usage = "applicable for Anthropic models, token allowance for thinking")
    private int thinkingTokenLimit;

    @Documented(usage = "applicable for OpenAI models, reasoning effort - low, medium or high")
    private String reasoningEffort;

    @Documented(usage = "Location where the results should be stored.  Useful for media generation")
    private String outputLocation;

    // Audio output
    private String voice;

    public String getPrompt() {
        return instructions;
    }
}
