# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Publish Java Client v4 to Maven Central

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish (e.g., v1.0.0)'
        required: true
      maven_central:
        description: 'Publish to Maven Central'
        required: true
        default: 'true'

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: prod
    name: Gradle Build and Publish
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up Zulu JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Publish
        run: |
          export VERSION="${{ github.event.inputs.version }}"
          export CONDUCTOR_CLIENT_VERSION=`echo ${VERSION:1}`
          echo Publishing version $CONDUCTOR_CLIENT_VERSION
          cd conductor-clients/java/conductor-java-sdk
          ./gradlew publish -Pversion=$CONDUCTOR_CLIENT_VERSION -PmavenCentral=${{ github.event.inputs.maven_central }} -Pusername=${{ secrets.SONATYPE_USERNAME }} -Ppassword=${{ secrets.SONATYPE_PASSWORD }}
    env:
      ORG_GRADLE_PROJECT_signingKeyId: ${{ secrets.SIGNING_KEY_ID }}
      ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SIGNING_KEY }}
      ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGNING_PASSWORD }}

