name: Java Client v4 Build

on:
  push:
    branches:
      - main
    paths:
      - 'conductor-clients/java/conductor-java-sdk/**'
  pull_request:
    branches:
      - main
    paths:
      - 'conductor-clients/java/conductor-java-sdk/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Java Client v4 Build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Zulu JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "17"
      - name: Build
        run: |
          cd conductor-clients/java/conductor-java-sdk
          ./gradlew clean build -x :tests:build
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          report_paths: 'conductor-clients/java/**/build/test-results/test/TEST-*.xml'

